# Generated by Django 3.0.2 on 2020-01-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyper_leaque_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='winner',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=255),
        ),
    ]
