# Generated by Django 3.0.2 on 2020-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyper_leaque_backend', '0002_auto_20200122_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='away_team_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='home_team_score',
            field=models.IntegerField(default=0),
        ),
    ]
